"""Initial schema: profiles, pipeline runs, queries, recommendations

Revision ID: 5dc427373fa4
Revises: 
Create Date: 2026-07-19 15:56:14.764945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc427373fa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_profiles_domain'), ['domain'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('profile_uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('queries_discovered', sa.Integer(), nullable=False),
    sa.Column('queries_scored', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_uuid'], ['business_profiles.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_profile_uuid'), ['profile_uuid'], unique=False)

    op.create_table('discovered_queries',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('profile_uuid', sa.String(length=36), nullable=False),
    sa.Column('run_uuid', sa.String(length=36), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('estimated_search_volume', sa.Integer(), nullable=False),
    sa.Column('competitive_difficulty', sa.Integer(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('domain_visible', sa.Boolean(), nullable=True),
    sa.Column('visibility_position', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_uuid'], ['business_profiles.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_uuid'], ['pipeline_runs.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('discovered_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_queries_opportunity_score'), ['opportunity_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_queries_profile_uuid'), ['profile_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_queries_run_uuid'), ['run_uuid'], unique=False)

    op.create_table('content_recommendations',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('profile_uuid', sa.String(length=36), nullable=False),
    sa.Column('query_uuid', sa.String(length=36), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('target_keywords', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_uuid'], ['business_profiles.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_uuid'], ['discovered_queries.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('content_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_recommendations_profile_uuid'), ['profile_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_recommendations_query_uuid'), ['query_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_recommendations_query_uuid'))
        batch_op.drop_index(batch_op.f('ix_content_recommendations_profile_uuid'))

    op.drop_table('content_recommendations')
    with op.batch_alter_table('discovered_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_queries_run_uuid'))
        batch_op.drop_index(batch_op.f('ix_discovered_queries_profile_uuid'))
        batch_op.drop_index(batch_op.f('ix_discovered_queries_opportunity_score'))

    op.drop_table('discovered_queries')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_profile_uuid'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_profiles_domain'))

    op.drop_table('business_profiles')
    # ### end Alembic commands ###
